idf_component_register(
    SRCS
      "LoraProgrammer.c"
      "kuart.c"
      "RF1216.c"
      "kwifi.c"
      "kmdns.c"
      "klittlefs.c"
      "kdatetime.c"
      "kota.c"
      "krest.c"
    INCLUDE_DIRS
      "."
      "include"
    REQUIRES
      cjson
      esp_driver_gpio
      esp_http_server
      esp_wifi
      esp_timer
      nvs_flash
      app_update
)
